version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'  # 通常の本番用ポート
    restart: always  # 障害が発生した場合に自動再起動
    networks:
      - app-network
networks:
  app-network:
    driver: bridge