FROM node:22-alpine

# 環境変数の設定
ENV CHOKIDAR_USEPOLLING=true
ENV HOST=0.0.0.0
ENV PORT=3001

# 作業ディレクトリを設定
WORKDIR /app

# アプリケーションの依存関係をインストール
COPY package.json yarn.lock ./
RUN yarn install

# アプリケーションのソースコードをコピー
COPY . .

# Prismaの生成（本番環境用）
RUN npx prisma generate

# 本番用にアプリをビルド
RUN yarn build

# ポートを公開
EXPOSE 3001

# アプリケーションを起動
CMD ["npx", "remix-serve", "build/"]
