FROM node:22-alpine

# 作業ディレクトリを設定
WORKDIR /app

# アプリケーションの依存関係をインストール
COPY package.json yarn.lock ./
RUN yarn install 
#--production  # 本番用に依存関係をインストール

# アプリケーションのソースコードをコピー
COPY . .

# Prismaの生成（本番環境用）
RUN npx prisma generate

# 本番用にアプリをビルド
RUN yarn build

# ポートを公開
EXPOSE 3001

# アプリケーションを起動
# CMD ["yarn", "start", "--host", "0.0.0.0" ,"--port ${PORT:-3000}"]
CMD ["sh", "-c", "HOST=0.0.0.0 PORT=${PORT:-3001} npx remix-serve build/index.js"]